/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myjni_bill_myjnidemo_JniTest */

#ifndef _Included_com_myjni_bill_myjnidemo_JniTest
#define _Included_com_myjni_bill_myjnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myjni_bill_myjnidemo_JniTest
 * Method:    javaCallC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myjni_bill_myjnidemo_JniTest_javaCallC
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_myjni_bill_myjnidemo_JniTest
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myjni_bill_myjnidemo_JniTest_helloFromC
        (JNIEnv *, jobject);




/*
 * Class:     com_myjni_bill_myjnidemo_JniTest
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myjni_bill_myjnidemo_JniTest_getStringFormC
        (JNIEnv *, jclass);

/*
 * Class:     com_myjni_bill_myjnidemo_JniTest
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_myjni_bill_myjnidemo_JniTest_getKeyValue
        (JNIEnv *, jclass);

/*
 * Class:     com_myjni_bill_myjnidemo_JniTest
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_myjni_bill_myjnidemo_JniTest_getIv
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
